// Package compiler turns a rule set into the bash script the ZFW engine
// applies. Each rule becomes iptables commands in ZFW-IN (host-native) and/or
// DOCKER-USER (published container ports); rule order is preserved within
// each chain. Zone "auto" is resolved per port via the dockerPorts map; a
// source of type "country" matches an ipset loaded from geoFiles.
package compiler

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/chicohaager/zfw/internal/geo"
	"github.com/chicohaager/zfw/internal/rules"
)

// Compile returns the bash ruleset script.
//   - dockerPorts marks which TCP ports are Docker-published (resolves zone "auto").
//   - geoFiles maps a lowercase country code to its ipset-restore file path;
//     these sets are loaded before the rules that reference them.
func Compile(rs rules.RuleSet, dockerPorts map[int]bool, geoFiles map[string]string) string {
	var b strings.Builder
	b.WriteString("#!/bin/bash\n")
	b.WriteString("# Generated by zfwd — DO NOT EDIT. Source of truth: rules.json\n")
	b.WriteString("set -u\n")
	b.WriteString(`IPT="$(command -v iptables-legacy 2>/dev/null || command -v iptables)"` + "\n")
	b.WriteString(`IPT6="$(command -v ip6tables-legacy 2>/dev/null || command -v ip6tables 2>/dev/null || true)"` + "\n\n")

	// ---- geo country sets (ipset) ----
	if len(geoFiles) > 0 {
		b.WriteString("# ===== geo country sets (ipset) =====\n")
		b.WriteString("modprobe ip_set ip_set_hash_net xt_set 2>/dev/null || true\n")
		ccs := make([]string, 0, len(geoFiles))
		for cc := range geoFiles {
			ccs = append(ccs, cc)
		}
		sort.Strings(ccs)
		for _, cc := range ccs {
			f := geoFiles[cc]
			fmt.Fprintf(&b, "[ -r %q ] && ipset restore -exist -f %q\n", f, f)
		}
		b.WriteString("\n")
	}

	rl := append([]rules.Rule(nil), rs.Rules...)
	sort.SliceStable(rl, func(i, j int) bool { return rl[i].Order < rl[j].Order })

	// ---- ZFW-IN: host-native services ----
	b.WriteString("# ===== ZFW-IN (host-native services) =====\n")
	b.WriteString("$IPT -N ZFW-IN 2>/dev/null || true\n")
	b.WriteString("$IPT -F ZFW-IN\n")
	for _, base := range []string{
		"-m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
		"-m conntrack --ctstate INVALID -j DROP",
		"-i lo -j ACCEPT",
		"-i virbr0 -j ACCEPT",
		"-i tailscale0 -j ACCEPT",
		"-i zt+ -j ACCEPT",
		"-p icmp -j ACCEPT",
		"-p udp --dport 68 -j ACCEPT",
		"-p udp --dport 41641 -j ACCEPT",
		"-p udp --dport 9993 -j ACCEPT",
	} {
		fmt.Fprintf(&b, "$IPT -A ZFW-IN %s\n", base)
	}
	for _, r := range rl {
		if !r.Enabled {
			continue
		}
		for _, line := range hostLines(r, dockerPorts) {
			fmt.Fprintf(&b, "$IPT -A ZFW-IN %s\n", line)
		}
	}
	if rs.DefaultPolicy == "allow" {
		b.WriteString("$IPT -A ZFW-IN -j RETURN\n")
	} else {
		b.WriteString("$IPT -A ZFW-IN -j DROP\n")
	}
	b.WriteString("$IPT -C INPUT -j ZFW-IN 2>/dev/null || $IPT -I INPUT 1 -j ZFW-IN\n\n")

	// ---- DOCKER-USER: published container ports ----
	b.WriteString("# ===== DOCKER-USER (published container ports) =====\n")
	b.WriteString("if $IPT -L DOCKER-USER -n >/dev/null 2>&1; then\n")
	b.WriteString("  $IPT -F DOCKER-USER\n")
	b.WriteString("  $IPT -A DOCKER-USER -m conntrack --ctstate ESTABLISHED,RELATED -j RETURN\n")
	b.WriteString("  $IPT -A DOCKER-USER -s 127.0.0.0/8 -j RETURN\n")
	if rs.HostIP != "" {
		fmt.Fprintf(&b, "  $IPT -A DOCKER-USER -s %s -j RETURN\n", rs.HostIP)
	}
	b.WriteString("  $IPT -A DOCKER-USER -i tailscale0 -j RETURN\n")
	b.WriteString("  $IPT -A DOCKER-USER -i zt+ -j RETURN\n")
	for _, r := range rl {
		if !r.Enabled {
			continue
		}
		for _, line := range dockerLines(r, dockerPorts) {
			fmt.Fprintf(&b, "  $IPT -A DOCKER-USER %s\n", line)
		}
	}
	if rs.DefaultPolicy == "deny" && rs.LAN != "" {
		fmt.Fprintf(&b, "  $IPT -A DOCKER-USER -s %s -j DROP\n", rs.LAN)
	}
	b.WriteString("  $IPT -A DOCKER-USER -j RETURN\n")
	b.WriteString("fi\n\n")

	// ---- ZFW-IN6: IPv6 blocklist ----
	if len(rs.V6Drop) > 0 {
		b.WriteString("# ===== ZFW-IN6 (IPv6 blocklist) =====\n")
		b.WriteString(`if [ -n "$IPT6" ]; then` + "\n")
		b.WriteString("  $IPT6 -N ZFW-IN6 2>/dev/null || true\n")
		b.WriteString("  $IPT6 -F ZFW-IN6\n")
		b.WriteString("  $IPT6 -A ZFW-IN6 -m conntrack --ctstate ESTABLISHED,RELATED -j RETURN\n")
		b.WriteString("  $IPT6 -A ZFW-IN6 -i lo -j RETURN\n")
		for _, p := range rs.V6Drop {
			fmt.Fprintf(&b, "  $IPT6 -A ZFW-IN6 -p tcp --dport %d -j DROP\n", p)
		}
		b.WriteString("  $IPT6 -A ZFW-IN6 -j RETURN\n")
		b.WriteString("  $IPT6 -C INPUT -j ZFW-IN6 2>/dev/null || $IPT6 -I INPUT 1 -j ZFW-IN6\n")
		b.WriteString("fi\n")
	}
	return b.String()
}

// hostLines returns the iptables args (after "-A ZFW-IN") for a rule's
// host-targeted portion, or nil if the rule does not target the host chain.
func hostLines(r rules.Rule, dockerPorts map[int]bool) []string {
	all, ports, ok := portsForZone(r, dockerPorts, "host")
	if !ok {
		return nil
	}
	target := "ACCEPT"
	if r.Action == "deny" {
		target = "DROP"
	}
	var lines []string
	for _, src := range sourceArgs(r.Source) {
		if all {
			if r.Protocol == "both" {
				lines = append(lines, joinArgs(src, "-j", target))
			} else {
				lines = append(lines, joinArgs(src, "-p", r.Protocol, "-j", target))
			}
			continue
		}
		for _, proto := range protoList(r.Protocol) {
			lines = append(lines, joinArgs(src, "-p", proto, multiport(ports), "-j", target))
		}
	}
	return lines
}

// dockerLines returns the iptables args (after "-A DOCKER-USER") for a rule's
// docker-targeted portion. Published ports are matched on the original
// (pre-DNAT) destination port via conntrack.
func dockerLines(r rules.Rule, dockerPorts map[int]bool) []string {
	all, ports, ok := portsForZone(r, dockerPorts, "docker")
	if !ok {
		return nil
	}
	target := "RETURN" // allow: hand back to Docker's accept path
	if r.Action == "deny" {
		target = "DROP"
	}
	var lines []string
	for _, src := range sourceArgs(r.Source) {
		if all {
			if r.Protocol == "both" {
				lines = append(lines, joinArgs(src, "-j", target))
			} else {
				lines = append(lines, joinArgs(src, "-p", r.Protocol, "-j", target))
			}
			continue
		}
		for _, proto := range protoList(r.Protocol) {
			for _, p := range ports {
				lines = append(lines, joinArgs(src, "-p", proto,
					"-m", "conntrack", "--ctorigdstport", strconv.Itoa(p), "-j", target))
			}
		}
	}
	return lines
}

// portsForZone splits a rule's ports between the host chain and the docker
// chain, honouring rule.Zone (with "auto" resolved per port via dockerPorts).
func portsForZone(r rules.Rule, dockerPorts map[int]bool, want string) (all bool, ports []int, ok bool) {
	switch r.Zone {
	case "host":
		if want != "host" {
			return false, nil, false
		}
		if r.Ports.Type == "all" {
			return true, nil, true
		}
		return false, r.Ports.List, true
	case "docker":
		if want != "docker" {
			return false, nil, false
		}
		if r.Ports.Type == "all" {
			return true, nil, true
		}
		return false, r.Ports.List, true
	default: // auto
		if r.Ports.Type == "all" {
			if want == "host" {
				return true, nil, true
			}
			return false, nil, false
		}
		var hp, dp []int
		for _, p := range r.Ports.List {
			if dockerPorts[p] {
				dp = append(dp, p)
			} else {
				hp = append(hp, p)
			}
		}
		if want == "host" {
			if len(hp) == 0 {
				return false, nil, false
			}
			return false, hp, true
		}
		if len(dp) == 0 {
			return false, nil, false
		}
		return false, dp, true
	}
}

// sourceArgs returns the iptables match fragment(s) for a rule's source. A
// country source yields one fragment per country (an ipset match).
func sourceArgs(s rules.Source) []string {
	switch s.Type {
	case "ip", "range":
		return []string{"-s " + s.Value}
	case "country":
		var out []string
		for _, cc := range rules.SplitCountries(s.Value) {
			out = append(out, "-m set --match-set "+geo.SetName(cc)+" src")
		}
		if len(out) == 0 {
			return []string{""}
		}
		return out
	default: // any
		return []string{""}
	}
}

func protoList(p string) []string {
	if p == "both" {
		return []string{"tcp", "udp"}
	}
	return []string{p}
}

func multiport(ports []int) string {
	if len(ports) == 1 {
		return "--dport " + strconv.Itoa(ports[0])
	}
	ss := make([]string, len(ports))
	for i, p := range ports {
		ss[i] = strconv.Itoa(p)
	}
	return "-m multiport --dports " + strings.Join(ss, ",")
}

func joinArgs(parts ...string) string {
	var nn []string
	for _, p := range parts {
		if p != "" {
			nn = append(nn, p)
		}
	}
	return strings.Join(nn, " ")
}
